### ISSUE TITLE
Project Review

### ISSUE THREAD

**Issue by rahulkore** [jithstephen13/TradeMart#62]
# Review Comments
- UI Aspects
  - Pros
    - UI looks descent 
    - many number of components are present.
    - Functionality wise , it is rich in functionalities.
    - wireframing looks good.
    - Redux arch is used correctly.
    
  - Cons
     - Localization is not done correctly
	 - No client side data validation
     - Some links are broken . 
     - Not much comments are present in code.
  
 
  

- Overall Comments 
  - Little more focus on back end could have been great .
  - some of the components from UI could have been reduced and that much effort could have been given to back end side development .
  - coding standard , functionality all are maintained at a good quality .
  - use of git is done very good , design patterns are good .
  - no of components could've been reduced and those efforts could've been utilized on making the components working .
  - Next time focus on workable features rather than more no of features . 
  - Don't keep any commented code.

**Comment by jithstephen13** [comment]
Thank you very much for your feedback about our project. I really appreciate the details you shared with me about areas I could improve on. This insight will help me a lot. I appreciate your guidance and hope we can find more feedback opportunities soon.
